export const OMIT_PRIM_CATS_SPENDING = [
  "INCOME",
  "TRANSFER_IN",
  "TRANSFER_OUT",
  "LOAN_PAYMENTS",
  "BANK_FEES",
  "RENT_AND_UTILITIES",
];

export const OMIT_DTLD_CATS_SPENDING = [
  "GENERAL_SERVICES_INSURANCE",
  "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT",
];

export const SPENDING_PRIM_CATS = [
  "ENTERTAINMENT",
  "FOOD_AND_DRINK",
  "GENERAL_MERCHANDISE",
  "HOME_IMPROVEMENT",
  "MEDICAL",
  "PERSONAL_CARE",
  "GENERAL_SERVICES",
  "GOVERNMENT_AND_NON_PROFIT",
  "TRANSPORTATION",
  "TRAVEL",
];

export const BILLS_PRIM_CATS = [
  "LOAN_PAYMENTS",
  "BANK_FEES",
  "RENT_AND_UTILITIES",
];

export const BILLS_DTLD_CATS = [
  "GENERAL_SERVICES_INSURANCE",
  "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT",
];

export const DTLD_DESC = {
  
}